runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /(.*)
  script: app.py
  secure: always
  redirect_http_response_code: 301 
- url: (www)(\.)(gradder)(\.)(io)(/)(.*)
  script: app.py
  secure: always
  redirect_http_response_code: 301
  
runtime_config:
 python_version: 3
