version: 2.1
jobs: 
  buildbackend: 
    working_directory: ../backend
    docker:
      - circleci/python:latest
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
          - save_cache:
              key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
              paths:
                - "venv"
      - run:
        - run:
          name: Running tests
          command: |
            . venv/bin/activate
              python3 tests.py
  buildfrontend:
    version: 2
jobs:
  build:
    docker: 
      - image: node:7.4.0
    working_directory: ../client
    steps:
      - checkout
      - run: mkdir -p ../backend/artifacts
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: artifacts
